name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn run build
      - name: Deploy
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          BRANCH: dist
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.DEPLOY_CONTAINER }}
          method: 'POST'
